# Generated by Django 3.1.2 on 2020-11-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHab',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_habitacion', models.CharField(max_length=50)),
                ('beneficios', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('caracteristicas', models.TextField(help_text='Defina todas las características de la habitación')),
                ('descripcion', models.TextField(help_text='Descripción de la habitación')),
                ('servicios', models.TextField(help_text='Defina los servicios de la habitación')),
                ('equipamiento', models.TextField(help_text='Defina el equipamiento de la habitación')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('id_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.tipohab')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField(help_text='Escriba solo los años')),
                ('email', models.EmailField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('password', models.CharField(help_text='El largo debe ser entre 8 y 20 caracteres', max_length=20)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.pais')),
            ],
        ),
    ]
